apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-user
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-user
    spec:
      containers:
        - env:
            - name: AWS_BUCKET
              value: arn:aws:s3:::images-bucket-1234567
            - name: AWS_PROFILE
              value: default
            - name: AWS_REGION
              value: us-east-1
            - name: JWT_SECRET
              value: testing
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: ""
            - name: POSTGRES_PASSWORD
              value: ''
            - name: POSTGRES_USERNAME
              value: ""
            - name: URL
              value: http://localhost:8080
          image: gorodishon/udagram-api-user:v1
          name: backend-user
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
